version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-backstage
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: backstage_plugin_app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backstage:
    build:
      context: ../..
      dockerfile: packages/backend/Dockerfile
    container_name: backstage-backend
    ports:
      - '80:7007'
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
    command:
      [
        'node',
        'packages/backend',
        '--config',
        'app-config.yaml',
        '--config',
        'app-config.production.yaml',
      ]

volumes:
  postgres_data:
